name: Azure Static Web Apps CI/CD with NX Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm ci

    - name: Build Projects
      run: npx nx run-many --target=build --all

    # Uncomment if you want to include test and lint steps
    # - name: Test Projects
    #   run: npx nx run-many --target=test --all

    # - name: Lint Projects
    #   run: npx nx run-many --target=lint --all

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_04E5C8C10 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        app_location: "/apps/vinylplatz" # Adjust if your app location is different
        # Specify the locations relative to your project structure
        api_location: "/apps/data-api" # Set this if your NestJS API should be deployed alongside
        output_location: "dist/apps/vinylplatz" # The output location after building your project

  # This job can be adjusted or removed depending on whether you need specific actions on PR close
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_04E5C8C10 }}
          action: "close"
