# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js and Angular apps to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
  
      - name: Install Nx CLI
        run: npm install -g nx
  
      - name: npm install, build, and test
        run: |
          npm install
          nx run vinylplatz:build
          nx run data-api:build
          npm run test

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/dist/apps/data-api/ && zip ${GITHUB_WORKSPACE}/data-api-release.zip ./* -r
          cd ${GITHUB_WORKSPACE}/dist/apps/vinylplatz/ && zip ${GITHUB_WORKSPACE}/vinylplatz-release.zip ./* -r

      - name: Upload vinylplatz artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: vinylplatz
          path: vinylplatz-release.zip

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip

  deploy-vinylplatz:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: vinylplatz

      - name: Unzip artifact for deployment
        run: unzip vinylplatz-release.zip

      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/apps/vinylplatz" # Update this path
          api_location: ""
          output_location: ""

  deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NxWorkshop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: 'dist/apps/data-api' # Update this path
